version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - pnpm run build

  docker-build:
    desc: Build the Docker image
    cmds:
      - sudo docker build --no-cache . -t bljohnsondev/bjohnsonnet:latest -t 192.168.0.4:5000/bljohnsondev/bjohnsonnet

  docker-push:
    desc: Push the docker image to remote
    deps:
      - docker-build
    cmds:
      - sudo docker push 192.168.0.4:5000/bljohnsondev/bjohnsonnet 

  default:
    cmds:
      - task: build
